server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/webflux_security
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/webflux_security
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

jwt:
  password:
    encoder:
      secret: 4M8ANEk-3ABXJ1VqL8a2ZKg2FfZgEe_Sdo4Dg3banlb
      iterations: 64
      keylength: 256
